# Generated by Django 3.0.2 on 2020-02-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymouscomment',
            options={'verbose_name': '익명게시판 댓글', 'verbose_name_plural': '익명게시판 댓글'},
        ),
        migrations.AlterModelTable(
            name='anonymouscomment',
            table='익명게시판 댓글',
        ),
    ]
