# Generated by Django 3.0.2 on 2020-02-02 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anonymous', '0003_anonymous_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymous',
            name='likes',
        ),
        migrations.AddField(
            model_name='anonymous',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='추천수'),
        ),
    ]
