# Generated by Django 3.0.2 on 2020-02-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0004_auto_20200202_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymous',
            name='hits',
        ),
    ]
