# Generated by Django 3.0.2 on 2020-02-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0005_remove_anonymous_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to='image_file/%Y/%m/%d', verbose_name='이미지'),
        ),
    ]
