# Generated by Django 3.0.2 on 2020-03-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0008_auto_20200226_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouscomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Anonymous', verbose_name='게시글'),
        ),
    ]
