# Generated by Django 3.0.2 on 2020-01-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='summernote/%Y/%m/%d', verbose_name='이미지'),
        ),
    ]
