# Generated by Django 3.0.2 on 2020-01-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0003_auto_20200129_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='댓글',
        ),
    ]
