# Generated by Django 3.0.2 on 2020-01-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0004_auto_20200129_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='writer',
        ),
    ]
