# Generated by Django 3.0.2 on 2020-01-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0005_auto_20200129_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='post',
        ),
    ]
