# Generated by Django 3.0.2 on 2020-01-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0008_comment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.PositiveIntegerField(default=0, verbose_name='답글위치'),
        ),
    ]
