# Generated by Django 3.0.2 on 2020-01-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0009_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.IntegerField(default=0, verbose_name='답글위치'),
        ),
    ]
