# Generated by Django 3.0.2 on 2020-02-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0010_auto_20200131_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='comments',
            field=models.PositiveIntegerField(default=0, verbose_name='댓글수'),
        ),
    ]
