# Generated by Django 3.0.2 on 2020-02-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0012_auto_20200201_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='category',
            field=models.CharField(choices=[('자유', '자유'), ('질문', '질문'), ('정보', '정보')], default='자유', max_length=18, verbose_name='분류'),
        ),
    ]
