# Generated by Django 3.0.2 on 2020-03-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0016_auto_20200226_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='free.Free', verbose_name='게시글'),
        ),
    ]
