# Generated by Django 3.0.2 on 2020-03-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0018_auto_20200311_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
    ]
