# Generated by Django 3.0.2 on 2020-03-11 11:00

from django.db import migrations, models
import notice.models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0019_free_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free',
            name='upload_images',
        ),
        migrations.AddField(
            model_name='free',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=notice.models.get_file_path, verbose_name='이미지파일'),
        ),
    ]
