# Generated by Django 3.0.2 on 2020-02-27 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0004_auto_20200226_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 17, 6, 56, 204130, tzinfo=utc), verbose_name='수정일'),
        ),
    ]
