# Generated by Django 3.0.2 on 2020-02-28 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0005_auto_20200227_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 3, 54, 6, 131672, tzinfo=utc), verbose_name='수정일'),
        ),
    ]
