# Generated by Django 3.0.2 on 2020-03-03 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0007_auto_20200301_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 18, 4, 37, 840341, tzinfo=utc), verbose_name='수정일'),
        ),
    ]
