# Generated by Django 3.0.2 on 2020-03-11 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0009_auto_20200304_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 16, 30, 29, 264576, tzinfo=utc), verbose_name='수정일'),
        ),
    ]
