# Generated by Django 3.0.2 on 2020-08-24 13:59

import anonymous.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('comments', models.PositiveIntegerField(default='0', verbose_name='댓글수')),
                ('image_files', models.ImageField(blank=True, null=True, upload_to=anonymous.models.get_image_path, verbose_name='이미지파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='이미지첨부파일명')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='추천수')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '익명게시판',
                'verbose_name_plural': '익명게시판',
                'db_table': '익명게시판',
            },
        ),
        migrations.CreateModel(
            name='AnonymousComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('reply', models.IntegerField(default=0, verbose_name='답글위치')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous.Anonymous', verbose_name='게시글')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='댓글작성자')),
            ],
            options={
                'verbose_name': '익명게시판 댓글',
                'verbose_name_plural': '익명게시판 댓글',
                'db_table': '익명게시판 댓글',
            },
        ),
    ]
