# Generated by Django 3.0.2 on 2020-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='department',
            field=models.CharField(blank=True, max_length=10, verbose_name='부서'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank',
            field=models.CharField(choices=[('1', '회장'), ('2', '부회장'), ('3', '부장'), ('4', '차장'), ('5', '부원')], max_length=10, verbose_name='직급'),
        ),
    ]
