# Generated by Django 3.0.2 on 2020-03-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20200305_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='location',
            field=models.CharField(max_length=16, verbose_name='연구실위치'),
        ),
    ]
