# Generated by Django 3.0.2 on 2020-02-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='grade',
            field=models.CharField(blank=True, choices=[('first', '1학년'), ('second', '2학년'), ('third', '3학년'), ('fourth', '4학년')], max_length=10, verbose_name='학년'),
        ),
    ]
