# Generated by Django 3.0.2 on 2020-03-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_timetable_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일'),
        ),
    ]
