# Generated by Django 3.0.2 on 2020-03-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20200302_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일'),
        ),
    ]
