# Generated by Django 3.0.2 on 2020-08-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circles_name', models.CharField(max_length=8, verbose_name='동아리이름')),
                ('introduce', models.TextField(verbose_name='동아리소개')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '동아리소개',
                'verbose_name_plural': '동아리소개',
                'db_table': '동아리소개',
            },
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labs_name', models.CharField(max_length=8, verbose_name='연구실이름')),
                ('location', models.CharField(max_length=16, verbose_name='연구실위치')),
                ('introduce', models.TextField(verbose_name='연구실소개')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '연구실소개',
                'verbose_name_plural': '연구실소개',
                'db_table': '연구실소개',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='이름')),
                ('part', models.CharField(choices=[('회장단', '회장단'), ('개발부', '개발부'), ('학술부', '학술부'), ('운영부', '운영부'), ('홍보부', '홍보부'), ('재정부', '재정부')], max_length=10, verbose_name='부서')),
                ('rank', models.CharField(choices=[('1', '회장'), ('2', '부회장'), ('3', '부장'), ('4', '차장'), ('5', '부원')], max_length=10, verbose_name='직급')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '학생회조직도',
                'verbose_name_plural': '학생회조직도',
                'db_table': '학생회조직도',
            },
        ),
    ]
