# Generated by Django 3.0.2 on 2020-01-22 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '공지사항 게시글', 'verbose_name_plural': '공지사항 게시글'},
        ),
        migrations.AlterField(
            model_name='notice',
            name='writer',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
