# Generated by Django 3.0.2 on 2020-01-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_notice_top_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='top_fixed',
            field=models.BooleanField(default=False, verbose_name='상단고정'),
        ),
    ]
