# Generated by Django 3.0.2 on 2020-02-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0009_auto_20200128_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to='upload_file/%Y/%m/%d', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='upload_file/%Y/%m/%d', verbose_name='이미지'),
        ),
    ]
