# Generated by Django 3.0.2 on 2020-03-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0010_auto_20200202_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='upload_file/%Y/%m/%d', verbose_name='이미지파일'),
        ),
    ]
