# Generated by Django 3.0.2 on 2020-03-09 03:59

from django.db import migrations, models
import notice.models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0011_auto_20200309_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to=notice.models.get_file_path, verbose_name='파일'),
        ),
    ]
