# Generated by Django 3.0.2 on 2020-03-09 11:30

from django.db import migrations, models
import notice.models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0013_auto_20200309_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='extension',
            field=models.CharField(max_length=10, null=True, verbose_name='첨부파일확장자'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='upload_images',
            field=models.FileField(blank=True, null=True, upload_to=notice.models.get_file_path, verbose_name='이미지파일'),
        ),
    ]
