# Generated by Django 3.0.2 on 2020-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0014_auto_20200309_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
    ]
