# Generated by Django 3.0.2 on 2020-03-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0015_notice_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='extension',
        ),
    ]
