# Generated by Django 3.0.2 on 2020-08-24 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_auto_20200824_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 19, 40, 45, 545327, tzinfo=utc), verbose_name='수정일'),
        ),
    ]
