# Generated by Django 3.0.2 on 2020-08-24 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0004_auto_20200824_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 19, 44, 28, 702959, tzinfo=utc), verbose_name='수정일'),
        ),
    ]
