# Generated by Django 3.0.2 on 2020-08-25 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0005_auto_20200824_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 12, 56, 29, 512031, tzinfo=utc), verbose_name='수정일'),
        ),
    ]
