# Generated by Django 3.0.1 on 2019-12-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, null=True, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='이름'),
        ),
    ]
