# Generated by Django 3.0.1 on 2019-12-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191228_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered_date',
        ),
    ]
