# Generated by Django 3.0.1 on 2020-01-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200112_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='circles',
            field=models.CharField(choices=[('NONE', '미가입'), ('NUX', 'NUXPIA'), ('NET', 'NET'), ('DOT', 'DOT-GABI'), ('IMA', 'IMAGINE'), ('PNN', 'P&N'), ('MEG', 'MEGA-BRAIN')], max_length=18, null=True, verbose_name='동아리'),
        ),
    ]
