# Generated by Django 3.0.2 on 2020-01-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200112_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.CharField(max_length=32, null=True, verbose_name='인증번호'),
        ),
    ]
