# Generated by Django 3.0.2 on 2020-01-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='학번'),
        ),
    ]
