# Generated by Django 3.0.2 on 2020-01-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200120_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(null=True, verbose_name='학번'),
        ),
    ]
