# Generated by Django 3.0.2 on 2020-02-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200214_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=8, null=True, verbose_name='이름'),
        ),
    ]
